added multiprocessed, added support for converting masks, depth and n…
Synthesis-AI-Dev/fisheye-distortion pull request #5
Opened 2020-09-14 02:50 UTC by Shreeyak

…ormals (1-channel, uint16, float16 or float32)

2020-09-14 02:51 UTC, Shreeyak commented
@adavydow For masks, depth and normals, we want to have nearest-neighbor interpolation during distortion. Could you add that fix?

2020-09-18 12:39 UTC, Shreeyak commented
Updated requirements and readme.

2020-09-18 13:33 UTC, adavydow commented on README.md
> +  segments: .segments.png  # Mask of all objects in scene. 8 or 16 bit PNG.
I'd prefer to infer # of channels and image type from the image itself and provide interpolation type as additional parameter.
I'm not sure if hardcoding scene type is reasonable here.

2020-09-18 13:37 UTC, adavydow commented on apply_fisheye_distortion.py
> +        _process_file(f_json=f_json, f_img=_f.path, dir_output=dir_output, dist_coeff=dist_coeff, mode=_f.mode,
Here None is allowed for f_rgb and f_segments, but _process_file does not accept None as f_img path.

2020-09-18 13:39 UTC, adavydow commented on apply_fisheye_distortion.py
> +            for _ in executor.map(process_files, json_filenames, rgb_filenames, segments_filenames,
Looks like this will not work if number of segments and rgb filenames mismatch.

2020-09-18 13:42 UTC, adavydow commented on apply_fisheye_distortion.py
> +            for _ in executor.map(process_files, json_filenames, rgb_filenames, segments_filenames,
Oh, ok. It will fail in check_num images then. Any reason check_num_images returns number of images as second element of the pair? It should always be equal to num_json, right?

2020-09-18 13:43 UTC, adavydow commented on apply_fisheye_distortion.py
> +    return image_filenames, num_images
Any reason to return num_images?

2020-09-18 13:44 UTC, adavydow commented on apply_fisheye_distortion.py
> +    return image_filenames, num_images
Got it, it can be 0.
Logic here is really hard to understand and follow.

2020-09-18 13:45 UTC, adavydow commented on apply_fisheye_distortion.py
> +def process_files(f_json: Path, f_rgb: Union[Path, None], f_segments: Union[Path, None], dir_output: Path,
Is this function needed? I think it'd be easier to just call process_file twice in the main loop.

2020-09-18 13:48 UTC, adavydow commented on apply_fisheye_distortion.py
> +        img_dist = img_dist.clip(0, 255).astype(np.uint8)
I'd prefer explicit rounding. Also, currently `0.9` is treated as `0` and you will almost never have pixels with value 255.

2020-09-18 13:54 UTC, adavydow requested changes
Major: the way to parse None for rgb or segment index is currently extremely overcomplicated and hard to follow.
Minor: do we need to hardcode scenetypes? Isn't passing only interpolation method and extension mask a more versatile solution?

2020-09-18 14:38 UTC, Shreeyak commented
> Major: the way to parse None for rgb or segment index is currently extremely overcomplicated and hard to follow.
> Minor: do we need to hardcode scenetypes? Isn't passing only interpolation method and extension mask a more versatile solution?

Both of these issues are intertwined. The aim of this repo is that we can process multiple types of files in one go (rgb, segments, depth, normals) instead of calling the script multiple times. I also don't want to give the interpolation as a user input since it will result in user errors.
The config file should be easily modified such that we only process the type of file we want. I'll rework the logic to make it easier to follow, and I'll also rework the config so it's easier to use as intended:

```yaml
dir_input: samples/
dir_output: samples/
workers: 0  # How many workers to use to convert files. 0 for all cores.
crop_and_resize_output: True  # Disable to get original distorted image
apply_dist:
  rgb: True
  segments: True

distortion_parameters:
  # Ref: https://docs.opencv.org/4.4.0/db/d58/group__calib3d__fisheye.html
  # These are the distortion parameters of the fisheye camera model as defined in the fisheye module of OpenCV 4.4.0
  k1: 0.17149
  k2: -0.27191
  k3: 0.25787
  k4: -0.08054

file_ext:
  rgb: .rgb.png
  segments: .segments.png  # Mask of all objects in scene. 8 or 16 bit PNG.
  info: .json  # Contains camera intrinsics
```

2020-09-18 14:39 UTC, Shreeyak commented on apply_fisheye_distortion.py
> +def process_files(f_json: Path, f_rgb: Union[Path, None], f_segments: Union[Path, None], dir_output: Path,
This part needs reworking. I want to process all types of files belonging to the same render ID before proceeding to the next render ID. 
I'll prob keep track of render ID directly and append the file extensions to get the various files.

2020-09-18 14:46 UTC, Shreeyak commented on README.md
> +  segments: .segments.png  # Mask of all objects in scene. 8 or 16 bit PNG.
This allows users to specify which types of files they want to convert. And allows multiple types of files to be converted at once, instead of calling the script multiple times.
While your approach would work better to accomodate for any file extension (eg .distorted.rgb.png), it puts the onus on the user to figure out the file extension for each type of file they want to convert. I prefer to code it into the config, since we have a few standard extensions (optionally, config value can be overridden).

What do you feel is better?

2020-09-18 16:12 UTC, adavydow commented on README.md
> +  segments: .segments.png  # Mask of all objects in scene. 8 or 16 bit PNG.
Personally I'd prefer to leave it for user, but I think both ways are ok.

2020-09-18 16:15 UTC, adavydow commented
I don't see how are this issues intertwined. The second one is not a big problem and I'm ok with it.
If you want to leave config as is, please process None's explicitly in the code. Current way of dealing with it is extremely overcomplicated and hard to understand/support.

2020-09-29 14:56 UTC, Shreeyak commented
After using the repo, it's clear that your suggested method is more flexible. I've updated the code according to your suggestions (user needs to supply the filename extention and the type of interpolation). This also simplifies the code and clears the issue you raised about dealing with "None's".

Since this script is needed now for some deliverables, I'll go ahead and merge the PR.

2020-09-29 14:56 UTC, merged

2020-09-29 15:03 UTC, Shreeyak commented on README.md
> +  segments: .segments.png  # Mask of all objects in scene. 8 or 16 bit PNG.
Pushed fix as suggested (leave it for user)

2020-09-29 15:03 UTC, Shreeyak commented on apply_fisheye_distortion.py
> +        _process_file(f_json=f_json, f_img=_f.path, dir_output=dir_output, dist_coeff=dist_coeff, mode=_f.mode,
Sorted in new fix

2020-09-29 15:04 UTC, Shreeyak commented on apply_fisheye_distortion.py
> +    return image_filenames, num_images
All this logic removed in new fix, since user specifies a single file ext to process.